PhotoMagic/Controllers/PhotoMagicController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PhotoMagic.ChangePhoto;
using PhotoMagic.Database;
using PhotoMagic.Models;

namespace PhotoMagic.Controllers
{
    public class PhotoMagicController : Controller
    {
        private IWebHostEnvironment _environment;
        private readonly PhotoMagicDbContext _dbContext;

        public PhotoMagicController(IWebHostEnvironment environment, PhotoMagicDbContext dbContext)
        {
            _environment = environment;
            _dbContext = dbContext;
        }

        // GET: PhotoMagicController
        public IActionResult Welcome()
        {
            ViewData["FooterIsVisible"] = true;
            return View();
        }

        public IActionResult Page(int page = 1)
        {
            
            string viewName = page switch
            {
                1 => "Ready",
                2 => "Camera",
                3 => "Approve",
                4 => "ChooseAIEffect",
                5 => "SaveOrShare",
                _ => "Welcome"
            };

            ViewData["CurrentPage"] = page;

            if (page == 3 && TempData["ImageModel"] != null)
            {
               return RedirectToAction(viewName, new ImageModel{FileName = TempData["ImageModel"].ToString() } );
            }

            return  RedirectToAction(viewName);
        }

        // GET: PhotoMagicController
        public IActionResult Ready()
        {
            ViewData["CurrentPage"] = 1;
            ViewData["FooterIsVisible"] = true;
            return View();
        }

        // GET: PhotoMagicController
        public IActionResult Camera()
        {
            ViewData["CurrentPage"] = 2;
            return View(new ImageModel());
        }
        
        [HttpPost]
        public IActionResult SaveImage()
        {
            ViewData["CurrentPage"] = 3;
            try
            {
                var files = HttpContext.Request.Form.Files;
                if (files != null)
                {
                    foreach (var file in files)
                    {
                        if (file.Length > 0)
                        {
                            var fileName = file.FileName;
                            var fileNameToStore = string.Concat(Convert.ToString(Guid.NewGuid()),
                                Path.GetExtension(fileName));
                            //  Path to store the snapshot in local folder
                            var filepath = Path.Combine(_environment.WebRootPath, "Photos") + $@"\{fileNameToStore}";

                            // Save image file in local folder
                            if (!string.IsNullOrEmpty(filepath))
                            {
                                using (FileStream fileStream = System.IO.File.Create(filepath))
                                {
                                    file.CopyTo(fileStream);
                                    fileStream.Flush();
                                }
                            }

                            return Json(fileNameToStore);

                            //// Save image file in database
                            //var imgBytes = System.IO.File.ReadAllBytes(filepath);
                            //if (imgBytes != null)
                            //{
                            //    if (imgBytes != null)
                            //    {
                            //        string base64String = Convert.ToBase64String(imgBytes, 0, imgBytes.Length);
                            //        string imageUrl = string.Concat("data:image/jpg;base64,", base64String);

                            //        // Code to store into database
                            //        // save filename and image url(base 64 string) to the database
                            //    }
                            //}
                        }
                    }
                    return Json(null);

                }

            }
            catch (Exception)
            {
                throw;
            }

            return RedirectToAction("Camera");

        }

        public IActionResult Approve(ImageModel imageModel)
        {
            ViewData["CurrentPage"] = 3;
            return View(imageModel);
        }



        public IActionResult ChooseAIEffect(ImageModel imageModel)
        {
            PhotoRoom photoRoom = new PhotoRoom(_environment);
            photoRoom.ChangePhoto(imageModel);

            ViewData["CurrentPage"] = 4;
            TempData["ImageModel"] = imageModel.FileName;
            return View(imageModel);
        }

        public IActionResult SaveOrShare(int page = 5)
        {
            ViewData["CurrentPage"] = 5;
            return View();
        }

        public IActionResult Finish()
        {
            ViewData["FooterIsVisible"] = true;
            return View();
        }

        public IActionResult BackToStart()
        {
            ViewData["FooterIsVisible"] = true;
            return RedirectToAction("Index", "Home");
        }

        //// GET: PhotoMagicController/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        //// GET: PhotoMagicController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: PhotoMagicController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: PhotoMagicController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: PhotoMagicController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: PhotoMagicController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: PhotoMagicController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

PhotoMagic/Views/PhotoMagic/Approve.cshtml
@model ImageModel;

@{
    ViewData["Title"] = "Approve";
}

<div class="container text-center">
    <div class="row">
        @await Html.PartialAsync("_navbarPartialView")
    </div>
    <div class="row">
        <img src="@Model.FilePath"/>
    </div>
    
    <div class="row">
        <form asp-controller="PhotoMagic" asp-action="ChooseAIEffect" method="post">
            <button type="submit" class="btn btn-lg d-flex align-items-center">Potwierdź</button>
            @Html.HiddenFor(m => m.FileName)
        </form>
        <form asp-controller="PhotoMagic" asp-action="Camera" method="post">
            <button type="submit" class="btn btn-lg d-flex align-items-center">Nowe Zdjęcie</button>
        </form>
    </div>

</div>

PhotoMagic/Views/PhotoMagic/Camera.cshtml
@model ImageModel

@{
    ViewData["Title"] = "Camera";
}


<div class="container text-center">
    <div class="row">
        @await Html.PartialAsync("_navbarPartialView")
    </div>
    <div class="row justify-content-center">
        <body class="container">
            <div class="col-md-6" style="padding-top:50px;">
                <div class="panel panel-default">
                    <div class="panel-heading">Live Web Camera</div>
                    <div class="panel-body">
                        <div id="LiveCamera" style="margin-bottom:50px;"></div>
                        <form>
                            <input type="button" class="btn btn-primary" value="Capture Snapshot" onClick="CaptureSnapshot()">
                        </form>
                        <form asp-controller="PhotoMagic" asp-action="Approve" method="post">
                            @Html.HiddenFor(m=>m.FileName)
                            <input type="submit" class="btn btn-primary" value="Przejdz dalej"></input>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-6" style="padding-top:50px;">
                <div class="panel panel-default">
                    <div class="panel-heading">Captured Snapshot/Image</div>
                    <div class="panel-body">
                        <div id="results">Your snapshot will appear here...</div>
                    </div>
                    <br />
                    <br />
                </div>
            </div>

            <!-- Include the Webcam.js JavaScript Library -->
            <script src="~/webcamjs/webcam.js"></script>
            <!-- Configure web cam settings -->
            <script language="JavaScript">
                Webcam.set({
                    width: 500,
                    height: 375,
                    image_format: 'png',
                    jpeg_quality: 100
                });
                Webcam.attach('#LiveCamera');
            </script>

            <!-- Javascript code to capture the snapshot and displaying it in the screen -->
            <script language="JavaScript">
                function CaptureSnapshot() {
                    Webcam.snap(function (data) {
                        // display results in page
                        document.getElementById('results').innerHTML = '<img src="' + data + '"/>';
                        // Send image data to the controller to store locally or in database
                        Webcam.upload(data,
                            '/PhotoMagic/SaveImage',
                            function (code, text) {
                                document.getElementById('FileName').value = text.replace('"', '').replace('"', '');       
                                //Post; odeslanie do kontrolera zeby wywowal akcje
                            });
                    });
                }
            </script>
        </body>
        

    </div>
</div>

<script>
    




</script>

PhotoMagic/Views/PhotoMagic/ChooseAIEffect.cshtml
@model ImageModel;

@{
    ViewData["Title"] = "ChooseAIEffect";
    
}

<div class="container text-center">
    <div class="row">
        @await Html.PartialAsync("_navbarPartialView")
    </div>
    <div class="row">
        <img src="@Model.FilePath"/>
    </div>
    <div class="row">
        <div class="container text-center">
            <div class="row row-cols-2 row-cols-lg-3 g-2 g-lg-3">
                <div class="col">
                    <div class="p-3">Efekt1</div>
                </div>
                <div class="col">
                    <div class="p-3">Efekt2</div>
                </div>
                <div class="col">
                    <div class="p-3">Efekt3</div>
                </div>
                <div class="col">
                    <div class="p-3">Efekt4</div>
                </div>
                <div class="col">
                    <div class="p-3">Efekt5</div>
                </div>
                <div class="col">
                    <div class="p-3">Efekt6</div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <form asp-controller="PhotoMagic" asp-action="SaveOrShare" method="post">
            @Html.HiddenFor(m=>m.FileName)
            <button type="submit" class="btn btn-lg d-flex align-items-center">Dalej</button>
        </form>
    </div>

</div>

PhotoMagic/Views/PhotoMagic/Finish.cshtml
@model PhotoMagic.Program

@{
    ViewData["Title"] = "Finish";
}

<div class="container text-center">
    <div class="row">
        <h1>Dziękujemy!</h1>
    </div>
    <div class="row">
        <h1>Twoje zdjęcie weźmie
            udział w konkursie
            organizowanym w
            naszym centrum!
            Wyniki sprawdzaj na
            wwww.silvertouch.pl</h1>
    </div>
    <div class="row">
        <form asp-controller="PhotoMagic" asp-action="BackToStart" method="post">
            <button type="submit" class="btn btn-lg d-flex align-items-center">Ok</button>
        </form>
    </div>

</div>

PhotoMagic/Views/PhotoMagic/Ready.cshtml
@model PhotoMagic.Program

@{
    ViewData["Title"] = "Ready";
}

<div class="container text-center">
    <div class="row">
        @await Html.PartialAsync("_navbarPartialView")
    </div> <div class="row">
        <p>Gotowy ?</p>
    </div>
    <div class="row">
        <p>Ustaw się na naszej </p>
        <p>ściance AI i wciśnij</p>
        <p>przycisk aparatu. Zrób</p>
        <p>zdjęcie i przejdź dalej.</p>
        <p>już teraz i zobacz, jakie</p>
        <p>efekty możesz uzyskać!</p>
    </div>
    <div class="row">
        <form asp-controller="PhotoMagic" asp-action="Camera" method="post">
            <button type="submit" class="btn btn-lg d-flex align-items-center">Click <span><i class="bi bi-camera2 d-flex mx-2 rounded-5 align-items-center bg-light justify-content-center"></i></span> </button>
        </form>
    </div>
    <div>
    </div>
</div>

PhotoMagic/Views/PhotoMagic/SaveOrShare.cshtml
@model PhotoMagic.Program

@{
    ViewData["Title"] = "SaveOrShare";
}

<div class="container text-center">
    <div class="row">
        @await Html.PartialAsync("_navbarPartialView")
    </div>
    <div class="row">
        <img src="/Content/Images/Logo.jpg" />
    </div>

    <div class="row">
        <form asp-controller="PhotoMagic" asp-action="Finish" method="post">
            <button type="submit" class="btn btn-lg d-flex align-items-center">Zapisz</button>
        </form>
        <form asp-controller="PhotoMagic" asp-action="Finish" method="post">
            <button type="submit" class="btn btn-lg d-flex align-items-center">Udostępnij</button>
        </form>
    </div>

</div>

PhotoMagic/Views/PhotoMagic/Welcome.cshtml
@model PhotoMagic.Program

@{
    ViewData["Title"] = "Welcome";
}

<div class="container text-center">
    <div class="row">
       Cześć!
    </div>
    <div class="row">
        <p>Przekształć swoje </p>
        <p>zdjęcia z łatwością</p>
        <p>dzięki mocy AI w</p>
        <p>PhotoMAGIC. Zacznij</p>
        <p>już teraz i zobacz, jakie</p>
        <p>efekty możesz uzyskać!</p>
    </div>
    <div class="row">
        <form asp-controller="PhotoMagic" asp-action="Ready" method="post">
            <div class="d-grid gap-2">
                <button class="btn btn-primary" type="submit">Dalej</button>
            </div>
        </form>
    </div>
    <div>
    </div>
</div>